os: osx
sudo: false

addons:
  sonarcloud:
    organization: "geoffray-adde-sonarsource-github"

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-macosx-x86 --out-dir bw-output xcodebuild -project sonar_scanner_example.xcodeproj -configuration Release
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
